### ISSUE TITLE
Laravel mix sourcemaps issue when using vuetable-2

### ISSUE THREAD

**Issue by isometriq** [ratiw/vuetable-2-with-laravel-5.4#9]
I am not able to use `.sourceMaps()` with laravel mix when  using vuetable-2.

Each component i used (3) yield an error, here is one of them (they are almost identical) :
```
error  in ./node_modules/vuetable-2/src/components/Vuetable.vue

Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\xampp\\htdocs\\vuetest\\node_modules\\vuetable-2"
    at C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xampp\htdocs\vuetest\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xampp\htdocs\vuetest\node_modules\babel-loader\lib\index.js:49:20)
    at C:\xampp\htdocs\vuetest\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (C:\xampp\htdocs\vuetest\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

 @ ./node_modules/vuetable-2/src/components/Vuetable.vue 8:2-219
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Listing.vue
 @ ./resources/assets/js/components/Listing.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/UsersListing.vue
 @ ./resources/assets/js/components/UsersListing.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

Tried with these package installed, but it does not help
```
"babel-plugin-transform-runtime": "^6.23.0",
"babel-preset-es2015": "^6.24.1",
```

Everything builds fine (with sourcemaps) when I comment the components including vuetable-2 components.

Do you have an idea why ?

**Comment by isometriq** [comment]
I was able to make it work ..i must be blind, instead of the above in the `package.json` I used these, like you did in this repo:
```
"babel-plugin-transform-runtime": "^6.23.0",
"babel-preset-stage-2": "^6.24.1",
```
